version: "3.8"

services:
  postgres:
    image: postgres:alpine
    container_name: shortlinks_pg
    ports:
      - "5435:5432"
    restart: always
    environment:
      POSTGRES_USER: pgdocker
      POSTGRES_PASSWORD: pgpassword
      POSTGRES_DB: shortlinks
    volumes:
      - ./.db-postgres-bitname:/var/lib/postgresql/data

  redis:
    image: bitnami/redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=docker
    volumes:
      - ./.db-redis-bitname:/var/lib/postgresql/data

volumes:
  .db-postgres-bitname:
  .db-redis-bitname:
